vich_uploader:
    db_driver: orm

    mappings:
       sliders:
           uri_prefix: /images/slider
           upload_destination: '%kernel.project_dir%/public/images/slider'
       chambres:
           uri_prefix: /images/chambre
           upload_destination: '%kernel.project_dir%/public/images/chambre'
       actus:
           uri_prefix: /images/actu
           upload_destination: '%kernel.project_dir%/public/images/actu'
       services:
           uri_prefix: /images/service
           upload_destination: '%kernel.project_dir%/public/images/service'
